### PR TITLE
Fix compact event field decoding

### LINKED ISSUE #383: Events at Initialization phase are silently being ignored if `ImOnline::SomeOffline` event is present
Hi @ascjones,

I have been using and testing your latest branch [aj-config](https://github.com/paritytech/subxt/tree/aj-config) on my tools.

When subscribing to `Session::NewSession` events i have notice that these are currently being ignored if `offences.Offence` event is present.

My temporary workaround is to enforce `decode_raw::<Compact<u128>>(input, output)` if type matches `Type { path: Path { segments: [] }, type_params: [], type_def: Compact(TypeDefCompact { type_param: UntrackedSymbol { id: 6, marker: PhantomData } }), docs: [] }`, probably not the best approach but it's working fine so far.

The workaround is implemented [here](https://github.com/turboflakes/subxt/blob/e7d58bc93da2a479234ca2f6eb96f48a0ee5a297/src/events.rs#L319). 

I find it tricky to present a test so that this could be easier replicated.  But when inspecting Kusama block [10819134](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/10819134) and hardcoding this block when subscribing the latest block made my life easier to troubleshoot this issue :)

This branch with the hardcoded block [10819134](https://github.com/turboflakes/subxt/blob/ade33a5f817c2f0e3def28ea1483c086f5ee2d41/src/subscription.rs#L224)  can easily replicate the problem [pm-test-inspect-specific-block](https://github.com/turboflakes/subxt/blob/pm-test-inspect-specific-block/examples/fetch_block.rs) when running the example `RUST_LOG=subxt=debug cargo watch -x 'run --example fetch_block'`.

If anyone could have a look at this issue and confirm the best solution to solve it would be great.

### PR DESCRIPTION
**Pull request by ascjones**
Events with compact fields were failing to be decoded. Adds unit tests for event decoding.

Fixes https://github.com/paritytech/subxt/issues/383#issuecomment-1005553251

### CODE REVIEW

**Comment by paulormart** [comment]
Thanks for this @ascjones.

Not particular related to the fix of this PR, but it seems that the latest updates of `jsonrpsee` brakes the `fetch_remote` example which is needed from my side to validate this PR. On my fork i'm still using a really old version of `jsonrpsee`

Are you able to run this `cargo watch -x 'run --example fetch_remote'`? 

When setting `.set_url("ws://rpc.polkadot.io:80")` as suggested from the error message i still get `Error: Rpc(Transport(Invalid URL: URL scheme not supported, expects 'ws'))`

**Comment by niklasad1** [comment]
@paulormart 

please open an issue in `jsonrpsee` but the issue is that you got a HTTP redirection there...

```
target: Target { sockaddrs: [104.26.8.125:80, 104.26.9.125:80, 172.67.71.26:80, [2606:4700:20::681a:97d]:80, [2606:4700:20::ac43:471a]:80, [2606:4700:20::681a:87d]:80], host: "rpc.polkadot.io", host_header: "rpc.polkadot.io:80", _mode: Plain, path_and_query: "/" }
2022-01-05T15:32:34.132404Z DEBUG jsonrpsee_client_transport::ws: Connecting to target: Target { sockaddrs: [104.26.8.125:80, 104.26.9.125:80, 172.67.71.26:80, [2606:4700:20::681a:97d]:80, [2606:4700:20::ac43:471a]:80, [2606:4700:20::681a:87d]:80], host: "rpc.polkadot.io", host_header: "rpc.polkadot.io:80", _mode: Plain, path_and_query: "/" }
2022-01-05T15:32:34.266608Z DEBUG jsonrpsee_client_transport::ws: Redirection: status_code: 301, location: https://rpc.polkadot.io/
thread 'main' panicked at 'Some("https")', client/transport/src/ws/mod.rs:440:17
```

**Comment by paulormart** [comment]
Hi @ascjones this PR fixes #383

File: src/events.rs [hunk 1]
```diff
@@ -339,35 +339,118 @@ pub enum EventsDecodingError {
...
+
+        assert_eq!(events[0].1.variant_index, encoded_event[0]);
+        assert_eq!(events[0].1.data.0, encoded_event[1..]);
+    }
+
+    #[test]
+    fn compact_event_field() {
+        #[derive(Clone, Encode, TypeInfo)]
+        enum Event {
+            A(#[codec(compact)] u32),
```
Comment (jsdw) [inline src/events.rs:437]: This all looks good; is it worth adding another test to check that compact encoded structs containing a single compact-encoded field are ok too (it looks like the code handles them too)?

**Review by jsdw — APPROVED** [review]

File: src/events.rs (hunk 1 above)
Comment (ascjones) [reply src/events.rs:479]: Good idea, added some more tests. Can be more too still, but at least we now have a template for testing this component.

File: src/events.rs [hunk 2]
```diff
@@ -339,35 +339,187 @@ pub enum EventsDecodingError {
...
+            PalletMetadata,
+            RuntimeMetadataLastVersion,
+        },
+        RuntimeMetadataPrefixed,
+    };
+    use scale_info::{
+        meta_type,
+        TypeInfo,
+    };
+    use std::convert::TryFrom;
```
Comment (niklasad1) [inline src/events.rs:363]: we are on `edition 2021` right?

```suggestion
```

**Review by niklasad1 — APPROVED** [review]
LGTM, neat

File: src/lib.rs [hunk 3]
```diff
@@ -166,7 +166,7 @@ impl codec::Encode for Encoded {
 }
 
 /// A phase of a block's execution.
-#[derive(Clone, Debug, Eq, PartialEq, Decode)]
+#[derive(Clone, Debug, Eq, PartialEq, Decode, Encode)]
```
Comment (niklasad1) [inline src/lib.rs:169]: was this required `compact encoding/decoding` to work or a bonus? :)

Comment (ascjones) [reply src/lib.rs:169]: Just for the tests in order to encode some `EventRecord`s

File: src/events.rs (hunk 2 above)
Comment (ascjones) [reply src/events.rs:363]: Yes we are, sorry I missed this comment before merging :grimacing:
