### PR TITLE
Make EventSubscription and FilterEvents Send-able

### LINKED ISSUE #469: Unable to spawn Events Subscription
Hi guys!

Amazing work on the events subscription refactor!

I was wondering, what's the best way that we can spawn the Event subscription API inside a new thread?

Before it was possible, but since the last API we get something like;

```
the trait `std::marker::Send` is not implemented for `dyn futures::Future<Output = Result<subxt::Events<'_, DefaultConfig, substrate_client::polkadot::Event>, GenericError<std::convert::Infallible>>>`rustc
```

Thanks a lot!

### Code
```rust
    async_std::task::spawn(async {
        let api = ClientBuilder::new()
        .build()
        .await
        .unwrap()
        .to_runtime_api::<polkadot::RuntimeApi<DefaultConfig, DefaultExtra<DefaultConfig>>>();

        let mut balance_events =
            api.events().subscribe().await.unwrap().filter_events::<(
                polkadot::balances::events::Withdraw,
                polkadot::balances::events::Deposit,
            )>();

        // Our subscription will see all of the balance events we're filtering on:
        while let Some(ev) = balance_events.next().await {
            let event_details = ev.unwrap();

            let block_hash = event_details.block_hash;
            let event = event_details.event;
            println!("Event at {:?}:", block_hash);

            if let (Some(withdraw), _) = &event {
                println!("  Withdraw event: {withdraw:?}");
            }
        }
    });
 ```
 
 <details>
  <summary>Complete logs</summary>
  
  ```error: future cannot be sent between threads safely
  --> examples/examples/subscribe_some_events.rs:46:5
   |
46 |     async_std::task::spawn(async {
   |     ^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
   |
   = help: the trait `std::marker::Send` is not implemented for `dyn Iterator<Item = Result<FilteredEventDetails<subxt::sp_core::H256, (std::option::Option<balances::events::Withdraw>, std::option::Option<balances::events::Transfer>, std::option::Option<balances::events::Deposit>)>, GenericError<std::convert::Infallible>>>`
note: future is not `Send` as this value is used across an await
  --> examples/examples/subscribe_some_events.rs:60:30
   |
52 |         let mut balance_events =
   |             ------------------ has type `FilterEvents<'_, EventSubscription<'_, DefaultConfig, polkadot::Event>, DefaultConfig, (balances::events::Withdraw, balances::events::Transfer, balances::events::Deposit)>` which is not `Send`
...
60 |         while let Some(ev) = balance_events.next().await {
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here, with `mut balance_events` maybe used later
...
77 |     });
   |     - `mut balance_events` is later dropped here
note: required by a bound in `async_std::task::spawn`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.10.0/src/task/spawn.rs:28:29
   |
28 |     F: Future<Output = T> + Send + 'static,
   |                             ^^^^ required by this bound in `async_std::task::spawn`

error: future cannot be sent between threads safely
  --> examples/examples/subscribe_some_events.rs:46:5
   |
46 |     async_std::task::spawn(async {
   |     ^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
   |
   = help: the trait `std::marker::Send` is not implemented for `dyn futures::Future<Output = Result<subxt::Events<'_, DefaultConfig, polkadot::Event>, GenericError<std::convert::Infallible>>>`
note: future is not `Send` as this value is used across an await
  --> examples/examples/subscribe_some_events.rs:60:30
   |
52 |         let mut balance_events =
   |             ------------------ has type `FilterEvents<'_, EventSubscription<'_, DefaultConfig, polkadot::Event>, DefaultConfig, (balances::events::Withdraw, balances::events::Transfer, balances::events::Deposit)>` which is not `Send`
...
60 |         while let Some(ev) = balance_events.next().await {
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here, with `mut balance_events` maybe used later
...
77 |     });
   |     - `mut balance_events` is later dropped here
note: required by a bound in `async_std::task::spawn`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.10.0/src/task/spawn.rs:28:29
   |
28 |     F: Future<Output = T> + Send + 'static,
   |                             ^^^^ required by this bound in `async_std::task::spawn`

warning: `subxt-examples` (example "subscribe_some_events") generated 3 warnings
error: could not compile `subxt-examples` due to 2 previous errors; 3 warnings emitted
  ```
  </details>

### PR DESCRIPTION
**Pull request by jsdw**
Without this, they cannot be used in `tokio::spawn`-like contexts, which require things held across await points to impl `Send` (because they might be moved across threads between such points).

Closes #469

### CODE REVIEW

File: subxt/src/rpc.rs [hunk 1]
```diff
@@ -31,15 +31,13 @@ use crate::{
...
 };
 use codec::{
     Decode,
     Encode,
 };
-use core::{
-    convert::TryInto,
-    marker::PhantomData,
-};
+use core::convert::TryInto;
```
Comment (ascjones) [inline subxt/src/rpc.rs:40]: Can we get rid of this import too now because edition 2021?

**Review by ascjones — COMMENTED** [review]
LGTM

**Review by ascjones — APPROVED** [review]

**Comment by vstakhov** [comment]
I can confirm that it works now, thank you!

**Comment by lemarier** [comment]
Thank you !

**Review by lexnv — APPROVED** [review]

File: subxt/src/rpc.rs (hunk 1 above)
Comment (jsdw) [reply subxt/src/rpc.rs]: Turns out we can :)
