### PR TITLE
chainHead: Adjust `chainHead_storage` api

### LINKED ISSUE #1081: Subxt integration tests failed against latest Substrate build.
The nightly CI run which downloads the latest version of Substrate ran into test failures, which likely means that there are breaking changes that need fixing in Subxt.

Go to https://github.com/paritytech/subxt/actions/workflows/nightly.yml to see details about the failure.

### PR DESCRIPTION
**Pull request by lexnv**
This PR keeps the `chainHead_storage` API in sync with the latest spec changes.

Closes: https://github.com/paritytech/subxt/issues/1081

### CODE REVIEW

**Review by jsdw — APPROVED** [review]
Nice!

File: subxt/src/rpc/types.rs [hunk 1]
```diff
@@ -728,6 +728,85 @@ mod as_string {
...
 
+/// The storage item received as paramter.
+#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
+#[serde(rename_all = "camelCase")]
+pub struct StorageQuery<Key> {
+    /// The provided key.
+    pub key: Key,
+    /// The type of the storage query.
+    #[serde(rename = "type")]
+    pub queue_type: StorageQueryType,
```
Comment (ascjones) [inline subxt/src/rpc/types.rs:739]:
```suggestion
    pub query_type: StorageQueryType,
```

**Review by ascjones — APPROVED** [review]
