### PR TITLE
error: `RpcError` with custom client error

### LINKED ISSUE #692: Make RpcError generic
I am unable to upgrade from `0.23.0` to `0.24.0` because we lost the `RpcError` type ([here](https://github.com/paritytech/subxt/commit/599107b4322d2b959e26d9cf5269bc1ed4375a8c#diff-10b6cfdc40206da284713a1b63cb97c62e45a6018d456d32078b128712f8ea91L39)) propagated from `jsonrpsee`. We use this to specifically match custom errors for transaction invalidity and for when the background service needs to be restarted. Instead of converting this error into a string the `RpcClientT` trait should have a generic parameter for the error.

### PR DESCRIPTION
**Pull request by lexnv**
This PR extends the `RpcError` error to support two variants:
- custom error originated from the RPC client (this is boxed to allow users to cast the error, without needlessly having the error generic)
- custom string originated from subxt (ie, parsing parameters). 

Closes #692.

### CODE REVIEW

File: subxt/src/error.rs [hunk 1]
```diff
@@ -102,10 +102,17 @@ impl From<DispatchError> for Error {
...
 #[error("RPC error: {0}")]
-pub struct RpcError(pub String);
+pub enum RpcError {
+    // Dev note: We need the error to be safely sent between threads
+    // for `subscribe_to_block_headers_filling_in_gaps` and friends.
+    /// Error related to the RPC client.
+    ClientError(Box<dyn std::error::Error + Send + 'static>),
+    /// Custom error.
+    Custom(String),
+}
```
Comment (jsdw) [inline subxt/src/error.rs:115]: I'm thinking to myself; can we avoid having the generic "custom" variant?

Looking at the code, we have two `RpcError::Custom("RPC subscription dropped".into())` calls to deal with and "RPC Params are expected to be an array but got {params}" error to handle.

I'm also thinking; if a custom implementation needs unique error variants, it's probably a good idea if that implementation defines it's own enum with whatever variants it cares about, and we return that directly.

Sooo, how about we:

- Replace `Custom` for `SubscriptionDropped` (and use that for those dropped errors)
- Turn the jsonrpsee "RPC Params are expected to be an array but got {params}" error into a panic, and make sure it's mentioned in the `RpcClientT` trait methods that implementations are free to panic if parameters are not a JSON array. (it should be that we only use this internally anyway, and we do enforce this in the higher level interface, so I'm ok to think of it as a programmer error if this condition is not upheld).

Comment (lexnv) [reply subxt/src/error.rs]: That does make sense! Thanks for the suggestions!

I think we should remove entirely the `prep_params_for_jsonrpsee` with the next jsonrpsee release that should include [this optimization](https://github.com/paritytech/jsonrpsee/issues/862) 😄

File: subxt/src/rpc/rpc_client_t.rs [hunk 2]
```diff
@@ -20,6 +20,11 @@ pub use serde_json::value::RawValue;
 /// the caller. This is the case because we want the methods to be object-safe (which prohibits
 /// generics), and want to avoid any unnecessary allocations in serializing/deserializing
 /// parameters.
+///
+/// # Note
+///
+/// Implementations are free to panic if the provided parameters are not a valid
+/// JSON Array.
```
Comment (jsdw) [inline subxt/src/rpc/rpc_client_t.rs:27]:
```suggestion
/// # Panics
///
/// Implementations are free to panic if the `RawValue`'s passed to `request_raw` or 
/// `subscribe_raw` are not JSON arrays. Internally, we ensure that this is always the case.
```

File: subxt/src/error.rs (hunk 1 above)
Comment (jsdw) [reply subxt/src/error.rs]: Yup, that was on my mind too; we'll be able to simplify this stuff soon anyway :)

**Review by jsdw — APPROVED** [review]
Great stuff!

**Review by niklasad1 — APPROVED** [review]
yepp, this will be useful :+1:
