### PR TITLE
metadata: Generate runtime outer enums if not present in V14

### LINKED ISSUE #1171: Panic upon establishing client connection
I am trying to connect to different nodes with the Subxt library and hit [this panic](https://github.com/paritytech/subxt/blob/12e343449eca10d8c3c4870f12c9c34605d78918/metadata/src/from_into/v14.rs#L321) when connecting to a specific node: `RuntimeCall exists in V14; qed`.  
Can you please make this an error instead of a panic so my program does not crash?

<details><summary>Stack trace</summary>
<p>

```pre
thread 'main' panicked at 'RuntimeCall exists in V14; qed', /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-metadata-0.31.0/src/from_into/v14.rs:319:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/option.rs:1952:5
   5: core::option::Option<T>::expect
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/option.rs:898:21
   6: subxt_metadata::from_into::v14::generate_outer_enums
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-metadata-0.31.0/src/from_into/v14.rs:311:21
   7: subxt_metadata::from_into::v14::v14_to_v15
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-metadata-0.31.0/src/from_into/v14.rs:156:23
   8: subxt_metadata::from_into::v14::<impl core::convert::TryFrom<frame_metadata::v14::RuntimeMetadataV14> for subxt_metadata::Metadata>::try_from
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-metadata-0.31.0/src/from_into/v14.rs:15:9
   9: <T as core::convert::TryInto<U>>::try_into
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/convert/mod.rs:755:9
  10: <subxt_metadata::Metadata as parity_scale_codec::codec::Decode>::decode
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-metadata-0.31.0/src/lib.rs:640:57
  11: <subxt::metadata::metadata_type::Metadata as parity_scale_codec::codec::Decode>::decode
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-0.31.0/src/metadata/metadata_type.rs:71:9
  12: subxt::rpc::rpc::Rpc<T>::metadata::{{closure}}
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-0.31.0/src/rpc/rpc.rs:401:34
  13: subxt::client::online_client::OnlineClient<T>::fetch_latest_stable_metadata::{{closure}}
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-0.31.0/src/client/online_client.rs:158:24
  14: subxt::client::online_client::OnlineClient<T>::fetch_metadata::{{closure}}
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-0.31.0/src/client/online_client.rs:144:57
  15: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
  16: <futures_util::future::join::Join3<Fut1,Fut2,Fut3> as core::future::future::Future>::poll
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/join.rs:55:33
  17: subxt::client::online_client::OnlineClient<T>::from_rpc_client::{{closure}}
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-0.31.0/src/client/online_client.rs:95:10
  18: subxt::client::online_client::OnlineClient<T>::from_url::{{closure}}
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-0.31.0/src/client/online_client.rs:79:57
  19: subquery::endpoints::{{closure}}::{{closure}}::{{closure}}
             at ./src/main.rs:46:42
  20: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/futures_unordered/mod.rs:518:17
  21: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  22: <futures_util::stream::stream::buffer_unordered::BufferUnordered<St> as futures_core::stream::Stream>::poll_next
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/buffer_unordered.rs:75:15
  23: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/collect.rs:50:26
  24: subquery::endpoints::{{closure}}
             at ./src/main.rs:59:10
  25: subquery::main::{{closure}}
             at ./src/main.rs:12:26
  26: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  27: tokio::runtime::coop::with_budget
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  28: tokio::runtime::coop::budget
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  29: tokio::runtime::park::CachedParkThread::block_on
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  30: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  31: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  32: tokio::runtime::context::runtime::enter_runtime
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  33: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  34: tokio::runtime::runtime::Runtime::block_on
             at /Users/vados/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  35: subquery::main
             at ./src/main.rs:20:5
  36: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details> 

Code for reproduction is here: [subquery.zip](https://github.com/paritytech/subxt/files/12709170/subquery.zip) (just `cargo r`).

### PR DESCRIPTION
**Pull request by lexnv**
This PR avoids panics while constructing the suxbt client from an unexpected metadata format.

In doing so, the subxt is more robust in connecting to custom chains that may define different metadata formats (such as `wss://c1.hashed.live:443`).

Panics originate from two paces while converting the metadata V14 to the latest format V15:
-expectation of extrinsic types in metadata
-expectation of outer enums `RuntimeCall` and `RuntimeError` being present

For the former case, errors are propagated back to the user avoiding panic.

In the latter case:
- `RuntimeCall` is searched in metadata
- an extra check is added to ensure it is an enum that was previously taken for granted
- when the `RuntimeCall` is not found, the `Call` enum is searched
- if neither `RuntimeCall` nor `Call` are found, an outer enum is generated

Closes: https://github.com/paritytech/subxt/issues/1171

### CODE REVIEW

File: metadata/src/from_into/v14.rs [hunk 1]
```diff
@@ -308,69 +310,116 @@ impl ExtrinsicPartTypeIds {
...
+            Some(ty.id)
         })
-        .expect("RuntimeEvent exists in V14; qed");
+    };
 
-    let call_ty = call_enum.id.into();
-    let event_ty = event_enum.id.into();
+    let call_enum = find_type("RuntimeCall").or_else(|| find_type("Call"));
+    let event_enum = find_type("RuntimeEvent").or_else(|| find_type("Event"));
+    let error_enum = find_type("RuntimeError").or_else(|| find_type("Error"));
```
Comment (jsdw) [inline metadata/src/from_into/v14.rs:341]: One issue: `RuntimeCall`, `RuntimeEvent` and `RuntimeError` are fairly unique names which are unlikely to be used for random other types. but `Call`, `Event` and `Error` are not, and in fact all of these names are used for other enums in the type registry (each pallet could have one or more of these types declared).

Is the `Call` enum that you found actually one of those per-pallet ones? I have a feeling though that possibly an old version of Substrate used `Call` rather than `RuntimeCall` or something like that, but can't remember for sure.

Anyway, in the generated polkakdot metadata, the types we want (`RuntimeCall` etc) are all at paths like `runtime_types::polkadot_runtime::RuntimeCall`, `runtime_types::polkadot_runtime::RuntimeError` and `runtime_types::polkadot_runtime::RuntimeEvent`. (other types all live in `runtime_types` but in other places). I wonder whether the `_runtime` part of the `polkadot_runtime` path can be used to help find these things. Or else, maybe we just return an error and don't try falling back to anything else.

File: metadata/src/from_into/v14.rs [hunk 2]
```diff
@@ -307,70 +309,81 @@ impl ExtrinsicPartTypeIds {
...
+            let TypeDef::Variant(_) = &ty.ty.type_def else {
+                return None;
             };
-            ident == "RuntimeEvent"
+
+            if path.is_none() {
+                let mut segments = ty.ty.path.segments.clone();
+                segments.pop();
+                path = Some(segments);
+            }
```
Comment (jsdw) [inline metadata/src/from_into/v14.rs:333]: It's a bit weird saving a path mutably like this I think. More code but IMO clearer would be something like this:

```rust
// here, return eg:
Some((ty.id, segments))

// and then:
let call_enumm = find_type("RuntimeCall");
let event_enumm = find_type("RuntimeEvent");
let error_enumm = find_type("RuntimeError");

// Pick a path to save any generated types to; aim to
// put them next to whatever existing type we find first,
// or fall back to dumping it in the "top level" runtime_types
// path.
let path = match (call_enum, event_enum, error_enum) {
    (Some(p), None, None) => p,
    (None, Some(p), None) => p,
    (None, None, Some(p)) => p,
    (None, None, None) => vec!["runtime_types".into()]
};

// ...
```

File: metadata/src/from_into/v14.rs (hunk 1 above)
Comment (lexnv) [reply metadata/src/from_into/v14.rs]: Yep that makes sense, checking if a `Call` is indeed the enum we are looking for can become quite tedious :D

I've changed the code to not have fallbacks; propagate the error back to the user and only generate the `RuntimeError` if not present, which seems to be more straight forward

**Comment by jsdw** [comment]
Is there any sensible way to test that we return gracefully (ie without a panic) in the cases where `Runtime*`'s aren't available; if so that would be really nice :)

File: metadata/src/from_into/v14.rs (hunk 2 above)
Comment (lexnv) [reply metadata/src/from_into/v14.rs:333]: I'll remove that bit; fun fact I had initially thought of something similar with `call.or(event).or(error)` :D

Comment (jsdw) [reply metadata/src/from_into/v14.rs:333]: Ooh yeah you're right; using `.or` would have been much more compact :D

**Review by tadeohepperle — APPROVED** [review]
Nice, good job!

**Review by jsdw — APPROVED** [review]
Looks good; nice one!

**Comment by kylezs** [comment]
We were on 0.31.0 and I was about to report a bug but thought I'd check later versions first, and saw it was fixed here 🙌  thanks.
