### PR TITLE
fix: substrate-runner support several rpc endpoints

### LINKED ISSUE #1735: Subxt integration tests failed against latest Substrate build.
The nightly CI run which downloads the latest version of Substrate ran into test failures, which likely means that there are breaking changes that need fixing in Subxt.

Go to https://github.com/paritytech/subxt/actions/workflows/nightly.yml to see details about the failure.

### PR DESCRIPTION
**Pull request by niklasad1**
Close #1735

### CODE REVIEW

File: testing/substrate-runner/src/lib.rs [hunk 1]
```diff
@@ -198,8 +198,15 @@ fn try_find_substrate_port_from_output(
             .map(|(_, port_str)| port_str);
 
         if let Some(line_port) = line_port {
+            // If more than one rpc server is started to the log will capture multiple ports:
```
Comment (niklasad1) [inline testing/substrate-runner/src/lib.rs:201]:
```suggestion
            // If more than one rpc server is started then the log will capture multiple ports:
```

File: testing/substrate-runner/src/lib.rs [hunk 2]
```diff
@@ -198,8 +198,15 @@ fn try_find_substrate_port_from_output(
             .map(|(_, port_str)| port_str);
 
         if let Some(line_port) = line_port {
+            // If more than one rpc server is started then the log will capture multiple ports:
+            // `addr=127.0.0.1:9944,[::1]:9944`
+            let mut ports = line_port.split(',');
+            let p = ports
+                .nth(0)
```
Comment (niklasad1) [inline testing/substrate-runner/src/lib.rs:205]:
```suggestion
                .next()
```

**Review by lexnv — APPROVED** [review]

File: testing/substrate-runner/src/lib.rs [hunk 3]
```diff
@@ -198,8 +198,15 @@ fn try_find_substrate_port_from_output(
...
+            // If more than one rpc server is started then the log will capture multiple ports:
+            // `addr=127.0.0.1:9944,[::1]:9944`
+            let mut ports = line_port.split(',');
+            let p = ports
+                .next()
+                .expect("Expected at least one port in log line");
+
             // trim non-numeric chars from the end of the port part of the line.
-            let port_str = line_port.trim_end_matches(|b: char| !b.is_ascii_digit());
+            let port_str = p.trim_end_matches(|b: char| !b.is_ascii_digit());
```
Comment (jsdw) [inline testing/substrate-runner/src/lib.rs:209]: That works, though one could probably shorten this all a little to:

```rust
let port_num: String = line_port.chars().take_while(|c| c.is_numeric()).collect();
```

**Review by jsdw — APPROVED** [review]
