### PR TITLE
codegen: Fetch and decode metadata version then fallback

### LINKED ISSUE #1091: How to declare metadata version
I am getting this error on upgrading from v0.29.0 to v0.30.0. I assume that it defaults to V15 metadata, but the runtimes it is calling do not return this. Can I declare V14 metadata, or does the metadata returned have a way to tell subxt which version it is?
```
error: Could not decode metadata, only V14 and V15 metadata are supported: Could not decode `RuntimeMetadataPrefixed.1`:
           Could not decode `RuntimeMetadata::V15.0`:
               Could not decode `RuntimeMetadataV15::extrinsic`:
                   Could not decode `ExtrinsicMetadata::extra_ty`:
                       Could not decode `UntrackedSymbol::id`:
                           out of range decoding Compact<u32>
 --> src/types.rs:3:1
  |
3 | / #[subxt::subxt(
4 | |     runtime_metadata_url = "wss://kusama-rpc.polkadot.io:443",
5 | |     derive_for_all_types = "PartialEq, Clone"
6 | | )]
  | |__^
  |
  = note: this error originates in the attribute macro `subxt::subxt` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by lexnv**
The https://github.com/paritytech/subxt/issues/1091 exposed an error on out-of-date chains in terms of metadata with the latest substrate.

The code could fetch the latest unstable metadata, but that metadata version would fail to decode.
Failing to decode the metadata is a terminal error in our codegen.

To mitigate this behavior, the codegen would fetch and decode the metadata, the fallback on fetching older versions if that fails.

The order of fetching operations:
1. Unstable if the `unstable-metadata` attribute is provided
3. V15
4. V14

This is a bit overkill but hopefully would continue to work fine with fallbacks always on stable v15 and v14.

Closes: https://github.com/paritytech/subxt/issues/1091

### CODE REVIEW

File: codegen/src/api/mod.rs [hunk 1]
```diff
@@ -94,15 +94,25 @@ pub fn generate_runtime_api_from_url(
...
-    // Fetch latest unstable version, if that fails fall back to the latest stable.
-    let bytes = match fetch_metadata_bytes_blocking(url, MetadataVersion::Unstable) {
-        Ok(bytes) => bytes,
-        Err(_) => fetch_metadata_bytes_blocking(url, MetadataVersion::Latest)?,
+    fn fetch_metadata(url: &Uri, version: MetadataVersion) -> Result<Metadata, CodegenError> {
+        let bytes = fetch_metadata_bytes_blocking(url, version)?;
+        Ok(Metadata::decode(&mut &bytes[..])?)
+    }
+
+    let metadata = match fetch_metadata(url, MetadataVersion::Unstable) {
```
Comment (jsdw) [inline codegen/src/api/mod.rs:102]: We shouldnt try to fetch unstable metadata now unless subxt has the unstable-metadata feature activated

one way to do this might be to expose from subxt eg a const boolean called UNSTABLE_METADATA that is true if the feature is enabled and false if it's not (via feature flag) and is doc(hidden).

this crate could then check that to decide whether to try and fetch unstable first.

Comment (jsdw) [reply codegen/src/api/mod.rs:102]: Actually that's no good because the crate doesn't depend on subxt. Let's just have it look for V15 and then V14, and optionally we can also add an "unstable_metadata" attr to enable it fetching unstable if we want :)

File: subxt/src/lib.rs [hunk 2]
```diff
@@ -294,6 +295,21 @@ pub mod ext {
...
+/// #[subxt::subxt(
+///     runtime_metadata_url = "wss://rpc.polkadot.io:443"
+///     unstable_metadata,
+/// )]
+/// mod polkadot {}
+/// ```
+///
 /// **Note**: At the moment, you must derive at least one of `codec::Encode` or `codec::Decode` or `scale_encode::EncodeAsType` or
 /// `scale_decode::DecodeAsType` (because we add `#[codec(..)]` attributes on some fields/types during codegen), and you must use this
 /// feature in conjunction with `runtime_types_only` (or manually specify a bunch of defaults to make codegen work properly when
```
Comment (jsdw) [inline subxt/src/lib.rs:315]: These lines are meant to be a part of the `no_default_derives` section :)

File: subxt/src/lib.rs [hunk 3]
```diff
@@ -294,6 +295,21 @@ pub mod ext {
 /// mod polkadot {}
 /// ```
 ///
+/// ## `unstable_metadata`
+///
+/// This attribute works only in combination with `runtime_metadata_url`. By default, the macro will fetch the latest stable
+/// version of the metadata from the target node. This attribute makes the codegen fetch the unstable version of the metadata.
+/// This can be useful in CI, but is **not recommended** in production code, since it runs at compile time and will cause
+/// compilation to fail if the node at the given address is unavailable or unresponsive.
```
Comment (jsdw) [inline subxt/src/lib.rs:303]:
```suggestion
/// This attribute works only in combination with `runtime_metadata_url`. By default, the macro will fetch the latest stable
/// version of the metadata from the target node. This attribute makes the codegen attempt to fetch the unstable version of 
/// the metadata first. This is **not recommended** in production code, since the unstable metadata a node is providing is likely 
/// to be incompatible with Subxt.
```

File: macro/src/lib.rs [hunk 4]
```diff
@@ -131,8 +133,15 @@ pub fn subxt(args: TokenStream, input: TokenStream) -> TokenStream {
     }
 
     let should_gen_docs = args.generate_docs.is_present();
+    let unstable_metadata = args.unstable_metadata.is_present();
     match (args.runtime_metadata_path, args.runtime_metadata_url) {
         (Some(rest_of_path), None) => {
+            if unstable_metadata {
+                abort_call_site!(
+                    "The 'unstable_metadata' is expected only for `runtime_metadata_url`"
```
Comment (jsdw) [inline macro/src/lib.rs:141]:
```suggestion
                    "The 'unstable_metadata' attribute requires `runtime_metadata_url`"
```

**Review by jsdw — APPROVED** [review]
Looks good to me; the builder pattern cleans things up a bit too :)

**Review by tadeohepperle — APPROVED** [review]
👍🏻
