### PR TITLE
Bugfix: trimmed metadata hash comparison fails in `is_codegen_valid_for`

### LINKED ISSUE #1286: codegen: is_codegen_valid_for doesn't work as expected for "trimmed metadata"
1. Generate metadata/codegen

```
$ subxt metadata --url wss://rpc.polkadot.io --pallets "ElectionProviderMultiPhase,System" -f bytes > metadata.scale
```

2. Connect to the same node and compare the metadata (this calls is_codegen_valid_for internally)

```
$ ./target/debug/staking-miner --uri wss://rpc.polkadot.io info
Remote_node:
{
  "spec_name": "polkadot",
  "impl_name": "parity-polkadot",
  "spec_version": 9431,
  "impl_version": 0,
  "authoring_version": 0,
  "transaction_version": 24,
  "state_version": 0
}
Compatible: NO
```

If one just generates "untrimmed metadata" it works as expected.

### PR DESCRIPTION
**Pull request by tadeohepperle**
Fixes #1286

## What is the bug:

Metadata can be trimmed with `Metadata::retain(..)`. This is done by the CLI tool, e.g. `subxt metadata --url wss://rpc.polkadot.io --pallets "ElectionProviderMultiPhase,System"` retains only the specified pallets.
When comparing the hash of trimmed metadata (metadata that contains only a limited number of pallets/runtime apis) with the hash of the original metadata using the hashers `only_these_pallets` / `only_these_runtime_apis`, the hashes were different. This comparison was made in the generated `is_codegen_valid_for` function.

## Reason for the bug

in `Metadata::retain(..)` 3 things happen:
- the unneeded pallets/apis are removed at the top level
- all types that only these pallets/apis used are removed as well
- the top level enums (call, event and error) are Variant types. The variants relating to unneeded pallets/apis are removed. This happens in `retain_pallets_in_runtime_outer_types()`.

The last point is what caused the bug:
When specifying `only_these_pallets` for a MetadataHasher, the variant types of the top level enums (call, event and error) were modified to discard unneded pallets before the hash is calculated. HOWEVER the same types can be included in other places of the metadata. In @niklasad1 case for the staking-miner, the `"Events"` storage entry of the `"System"` pallet, had a type of `Vec<Event>`, where `Event` is the event top level type. But we did not go through all types of the metadata checking for each one if they are a top level variant and modifying it accordingly before computing its hash.
==> This caused the bug. 

## Solution

To solve the bug, we need to change how `specific_pallets` is used in the `MetadataHasher::hash(..)` function. 
We compute the hashes of the 3 outer enums first, trimming them down to only the variants that refer to the pallets in  `specific_pallets`. In the rest of the function we often compute the hash of some type. Every time this happens, we pass the type ids and hashes of the 3 outer enums down in these recursive hash computations. Every time an outer enum type is encountered we just use the hash computed at the start.

Other change: I severly limited all caching (used to prevent infinite recursion). Now a new cache is created every time we resolve the hash of some type. -> Less Cache reuse than before -> Worse Performance but better consistency.

### Alternative solution (not implemented)

We could also just clone and trim the metadata when calling `MetadataHasher::hash()` and specific pallets/apis are set.
This is probably less performant, but maybe in the end easier and more consistent.

## Testing

Added a test to confirm this works and manually tested it for the example Niklas provided.

### CODE REVIEW

File: metadata/src/utils/validation.rs [hunk 1]
```diff
@@ -75,6 +75,7 @@ fn get_field_hash(
     registry: &PortableRegistry,
     field: &Field<PortableForm>,
     cache: &mut HashMap<u32, CachedHash>,
+    precomputed: Option<&HashMap<u32, [u8; HASH_LEN]>>,
```
Comment (niklasad1) [inline metadata/src/utils/validation.rs:78]: I find it a bit hard to distinguish between "cache and precomputed" here, to me those seems very similar and wonder if it makes sense to merge them to single type instead?

It looks like `cache` is an empty hashmap in plenty of places and precomputed is an Option<HashMap>... would be nice unify that

File: metadata/src/utils/validation.rs [hunk 2]
```diff
@@ -262,20 +295,29 @@ fn get_extrinsic_hash(
...
+                outer_enums_hashes,
+            ),
         )
     }
 
     bytes
 }
 
 /// Obtain the hash representation of the `frame_metadata::v15::OuterEnums`.
+/// Also returns a HashMap containing the individual hashes of the 3 otuer enums.
```
Comment (niklasad1) [inline metadata/src/utils/validation.rs:315]:
```suggestion
/// Also returns a HashMap containing the individual hashes of the 3 outer enums.
```

File: metadata/src/utils/validation.rs [hunk 3]
```diff
@@ -262,20 +295,29 @@ fn get_extrinsic_hash(
...
+                signed_extension.additional_ty,
+                outer_enums_hashes,
+            ),
         )
     }
 
     bytes
 }
 
 /// Obtain the hash representation of the `frame_metadata::v15::OuterEnums`.
```
Comment (niklasad1) [inline metadata/src/utils/validation.rs:314]: I would prefer:

```
/// Obtain the hash representation of the `frame_metadata::v15::OuterEnums` 
/// and individual hashes of the outer enums.
///
/// The individual hashes may be used to calculate recursive hash computations
///
```

**Comment by jsdw** [comment]
Generally looks good to me, but just a few bits:

Right now we have `get_type_hash`, `get_type_hash_with_precomputed` and `get_type_hash_recurse`. My ideal state would be that there weren't so many ways to get a type hash, but failing that, the short named one should be the default IMO, so I'd rename `get_type_hash` => `get_type_hash_without_precomputed` and ``get_type_hash_with_precomputed` => `get_type_hash`.

As Niklas said above, the presumputed `Option<HashMap<..>>` sitting next to the cache is confusing I think. I wouldn't merge it with the cache (we want to make a cache only once and not provide a way to create a cache such that it'll be reused if possible). What I'd do is make a new type (which also doesn't need to be a hashmap; we could optimise it since there are exactly 3 entries). Maybe something a bit like:

```rust
struct TopLevelEnumHashes(Option<[(u8, [u8; HASH_LEN]); 3]>);

impl TopLevelEnumHashes {
    pub fn new(
        error_hash: (u8, [u8; HASH_LEN]),
        event_hash: (u8, [u8; HASH_LEN]),
        call_hash: (u8, [u8; HASH_LEN])
    ) -> Self { .. }

    pub fn empty() -> Self {
        Self(None)
    }

    pub fn get(&self, idx: u8) -> Option<[u8; HASH_LEN]> {
        self.0.and_then(|hashes| 
            hashes.iter().find(|(i, _hash)| idx == i).map(|(_i, hash)| hash)
        )
    }
}
```

Then it's clear in all of the function signatures that use it that it's different from the cache, and if you had an `empty()` version of it then you could maybe scrap the niche `get_type_hash_without_precomputed` and in those cases just pass empty in to them.

File: metadata/src/utils/validation.rs (hunk 1 above)
Comment (jsdw) [reply metadata/src/utils/validation.rs:78]: I agree that it's confusing, although I wouldn't merge it with the cache (see comment below :))

Comment (niklasad1) [reply metadata/src/utils/validation.rs:78]: Also a type-alias for hash would nice to avoid repeating `[u8; HASH_LEN]`

**Comment by jsdw** [comment]
Side note: weird test failure! I hope that doesn't relate to my unstable backend submit_extrinsic change! hopefully will work on a rerun but we should keep a close eye on that!

File: metadata/src/utils/validation.rs [hunk 4]
```diff
@@ -262,20 +295,29 @@ fn get_extrinsic_hash(
...
+/// Also returns a HashMap containing the individual hashes of the 3 otuer enums.
 fn get_outer_enums_hash(
     registry: &PortableRegistry,
     enums: &OuterEnumsMetadata,
     only_these_variants: Option<&[&str]>,
-) -> [u8; HASH_LEN] {
+) -> ([u8; HASH_LEN], HashMap<u32, [u8; HASH_LEN]>) {
```
Comment (niklasad1) [inline metadata/src/utils/validation.rs:320]: A separate type for the the `hash` + individual hashes for the outer enums hashes could maybe make sense.
Because documenting this is a little tricky

File: metadata/src/utils/validation.rs [hunk 5]
```diff
@@ -262,53 +300,95 @@ fn get_extrinsic_hash(
...
-        } else {
-            get_type_hash(registry, id, &mut HashMap::new())
+/// Hash representations of the `frame_metadata::v15::OuterEnums`.
+pub struct OuterEnumHashes {
+    call_hash: (u32, Hash),
+    error_hash: (u32, Hash),
+    event_hash: (u32, Hash),
+}
+
+impl OuterEnumHashes {
```
Comment (jsdw) [inline metadata/src/utils/validation.rs:318]: Small thing; perhaps move this to a separate `outer_enum_hashes.rs` file, just so that the "pub"s are respected :)

Looks great otherwise though!

File: metadata/src/utils/validation.rs [hunk 6]
```diff
@@ -207,11 +224,34 @@ impl CachedHash {
...
+/// Obtain the hash representation of a `scale_info::Type` identified by id.
+fn get_type_hash_recurse(
     registry: &PortableRegistry,
     id: u32,
     cache: &mut HashMap<u32, CachedHash>,
-) -> [u8; HASH_LEN] {
+    outer_enum_hashes: &OuterEnumHashes,
+) -> Hash {
+    // If the type is part of `precomputed` hashes, return the precomputed hash instead:
+
```
Comment (niklasad1) [inline metadata/src/utils/validation.rs:250]:
```suggestion
```

File: metadata/src/utils/validation.rs [hunk 7]
```diff
@@ -207,11 +224,34 @@ impl CachedHash {
...
+/// Obtain the hash representation of a `scale_info::Type` identified by id.
+fn get_type_hash_recurse(
     registry: &PortableRegistry,
     id: u32,
     cache: &mut HashMap<u32, CachedHash>,
-) -> [u8; HASH_LEN] {
+    outer_enum_hashes: &OuterEnumHashes,
+) -> Hash {
+    // If the type is part of `precomputed` hashes, return the precomputed hash instead:
```
Comment (niklasad1) [inline metadata/src/utils/validation.rs:249]: perhaps, tweak this comment now when "precomputed hashes" are called "outer_enum_hashes"?

**Review by niklasad1 — APPROVED** [review]
Looks great now

**Comment by jsdw** [comment]
Almost ready to merge I think; couple of small comments from Niklas to check out, move the `outer_enum_hashes` to a new file and confirm whether the test actually failed before or not and it's all good then from me :)

File: metadata/src/utils/validation.rs [hunk 8]
```diff
@@ -1080,4 +1175,144 @@ mod tests {
...
+            m
+        };
+
+        // test that the hashes are the same:
+        let hash = MetadataHasher::new(&metadata)
+            .only_these_pallets(&["First"])
+            .hash();
+        let hash_trimmed = MetadataHasher::new(&trimmed_metadata).hash();
+
+        assert_eq!(hash, hash_trimmed);
```
[the remark this answers is not in the document]
Comment (tadeohepperle) [reply metadata/src/utils/validation.rs:1316]: This test would have failed before the PR. The reason for the fail would have been that the metadata constructed here contains a `Vec<Events>` as a storage entry (which is an outer enum at the same time).

The recursive types issue we talked about is actually kind of seperate from this issue. It only happened to show that we had this recursive types issue in the solution I used in the first iteration of this PR (which I now closed): https://github.com/paritytech/subxt/pull/1301

So hopefully this PR solves both issues at once. We have always had a test for the [recursive types](https://github.com/paritytech/subxt/blob/tadeohepperle/bugfix-trimmed-metadata-enums/metadata/src/utils/validation.rs#L867), but it only passed because it did not cover critical cases, so it just happened to be a bad test.

File: metadata/src/utils/validation.rs [hunk 9]
```diff
@@ -262,53 +300,95 @@ fn get_extrinsic_hash(
...
-            get_type_hash(registry, id, &mut HashMap::new())
+/// Hash representations of the `frame_metadata::v15::OuterEnums`.
+pub struct OuterEnumHashes {
+    call_hash: (u32, Hash),
+    error_hash: (u32, Hash),
+    event_hash: (u32, Hash),
+}
+
+impl OuterEnumHashes {
+    /// Constructs new `OuterEnumHashes` from metadata. If `only_these_variants` is set, the enums are stripped down to only these variants, before their hashes are calculated.
```
Comment (lexnv) [inline metadata/src/utils/validation.rs:319]: nit; could break this doc on multiple lines

**Comment by tadeohepperle** [comment]
Thank you guys for reviewing, hmm interestingly the Unstable Backend Test time-outed again after 6h.

**Comment by jsdw** [comment]
> Thank you guys for reviewing, hmm interestingly the Unstable Backend Test time-outed again after 6h.

I'm going to look into that now a bit and see if I can find out what's going on there!

**Review by jsdw — APPROVED** [review]
Good stuff!

File: metadata/src/utils/validation/outer_enum_hashes.rs
Comment (jsdw) [inline metadata/src/utils/validation/outer_enum_hashes.rs:1]: Personally I'd have just had `utils/outer_enum_hashes` rather than the extra folder but it's all good!
