### PR TITLE
Fix decoding events via `.as_root_event()` and add test

### LINKED ISSUE #743: Runtime event parsing
It is currently not possible to parse the `runtime::Event` type. To hack around this it is possible to skip the `Phase` like such:  
```rust
let mut data = event.bytes();
let event = <(subxt::events::Phase, kusama::Event)>::decode(&mut data).map(|r| r.1);
```
But it would be nice to have something like `as_runtime_event`. I am not sure if `as_root_event` is supposed to do that, but it does not do.  
The advantage is that it would enable one to easily parse all events of a runtime, instead of just pallet specific ones.

### PR DESCRIPTION
**Pull request by jsdw**
Closes #743

### CODE REVIEW

File: subxt/src/events/events_type.rs [hunk 1]
```diff
@@ -201,10 +201,12 @@ pub struct EventDetails {
     all_bytes: Arc<[u8]>,
     // start of the bytes (phase, pallet/variant index and then fields and then topic to follow).
     start_idx: usize,
+    // start of the event (ie pallet/variant index and then the fields and topic after).
+    event_start_idx: usize,
     // start of the fields (ie after phase nad pallet/variant index).
```
Comment (lexnv) [inline subxt/src/events/events_type.rs:206]:
```suggestion
    // start of the fields (ie after phase and pallet/variant index).
```

**Review by lexnv — APPROVED** [review]

**Review by ascjones — APPROVED** [review]

**Review by Xanewok — APPROVED** [review]
