### PR TITLE
fix flaky testcase `full_client::client::unstable_rpcs::chainhead_v1_follow`

### LINKED ISSUE #1588: Flaky testcase `full_client::client::unstable_rpcs::chainhead_v1_follow`
### Explanation
The test fails because it asserts that finalized block hashes are exactly equal and doesn't account for chain progress that could happen, so the test will fail with an example error message: 
```bash 
thread 'full_client::client::unstable_rpcs::chainhead_v1_follow' panicked at testing/integration-tests/src/full_client/client/unstable_rpcs.rs:35:5:
assertion `left == right` failed
  left: Initialized(Initialized { finalized_block_hashes: [0xa7764f9b0dab002dc15d05faa51f9249190f89a8877470bd759d88683005f47b, 0x11cf3f55774cb66de344947198b5f26768d763c983ac53b243294bd1fe40066d], finalized_block_runtime: None })
 right: Initialized(Initialized { finalized_block_hashes: [0x11cf3f55774cb66de344947198b5f26768d763c983ac53b243294bd1fe40066d], finalized_block_runtime: None })
```
### Solution: 
in assertions check that `finalized_block_hashes` contain given `finalized_block_hash`

### PR DESCRIPTION
**Pull request by pkhry**
### Description: 
Close #1588 

### How to test: 
```bash
cargo test --package integration-tests --lib -- full_client::client::unstable_rpcs::chainhead_v1_follow --exact --show-output
```

### CODE REVIEW

File: testing/integration-tests/src/full_client/client/unstable_rpcs.rs [hunk 1]
```diff
@@ -32,12 +32,12 @@ async fn chainhead_v1_follow() {
...
     // The initialized event should contain the finalized block hash.
     let finalized_block_hash = legacy_rpc.chain_get_finalized_head().await.unwrap();
-    assert_eq!(
+    assert_matches!(
         event,
-        FollowEvent::Initialized(Initialized {
-            finalized_block_hashes: vec![finalized_block_hash],
-            finalized_block_runtime: None,
-        })
+        FollowEvent::Initialized(Initialized {finalized_block_hashes, finalized_block_runtime}) => {
```
Comment (niklasad1) [inline testing/integration-tests/src/full_client/client/unstable_rpcs.rs:37]:
```suggestion
        FollowEvent::Initialized(Initialized { finalized_block_hashes, finalized_block_runtime }) => {
```

**Review by niklasad1 — APPROVED** [review]

**Review by niklasad1 — APPROVED** [review]

**Review by jsdw — APPROVED** [review]
Nice one!
